server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: true
    key-store: /certs/shared-services.p12
    key-store-password: ${SHARED_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: bank-shared-tls

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth-service:8443/auth/jwks

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
        pool:
          max-idle-time: 5000
      default-filters:
        - RemoveRequestHeader=Cookie
      forwarded:
        enabled: true

      routes:
        - id: auth-api-docs
          uri: https://auth-service:8443
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: users-api-docs
          uri: https://user-service:8443
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: cards-api-docs
          uri: https://card-service:8443
          predicates:
            - Path=/cards/v3/api-docs
          filters:
            - RewritePath=/cards/(?<segment>.*), /$\{segment}

        - id: transfers-api-docs
          uri: https://transfer-service:8443
          predicates:
            - Path=/transfers/v3/api-docs,/analytics/v3/api-docs
          filters:
            - RewritePath=/transfers/(?<segment>.*), /$\{segment}


        - id: auth
          uri: https://auth-service:8443
          predicates:
            - Path=/auth/**

        - id: users
          uri: https://user-service:8443
          predicates:
            - Path=/users/**

        - id: cards
          uri: https://card-service:8443
          predicates:
            - Path=/cards/**

        - id: transfers
          uri: https://transfer-service:8443
          predicates:
            - Path=/transfers/**

        - id: analytics
          uri: https://transfer-service:8443
          predicates:
            - Path=/analytics/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: WARN

security:
  jwt:
    expected-issuer: ${AUTH_JWT_ISSUER:auth-service}
    accepted-audiences: ${GATEWAY_JWT_ACCEPTED_AUDIENCES:bank-rest-api}

springdoc:
  swagger-ui:
    persist-authorization: true
    urls:
      - name: auth
        url: /auth/v3/api-docs
      - name: users
        url: /users/v3/api-docs
      - name: cards
        url: /cards/v3/api-docs
      - name: transfers
        url: /transfers/v3/api-docs
    disable-swagger-default-url: true
    path: /swagger-ui.html

