server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: true
    key-store: /certs/shared-services.p12
    key-store-password: ${SHARED_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: bank-shared-tls
  forward-headers-strategy: framework

spring:
  application:
    name: transfer-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-transfer:5432/transfer}
    username: ${SPRING_DATASOURCE_USERNAME:transfer}
    password: ${SPRING_DATASOURCE_PASSWORD:transfer}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth-service:8443/auth/jwks
      client:
        registration:
          card-service:
            client-id: ${INTERNAL_CLIENT_TRANSFER_SERVICE_ID:transfer-service}
            client-secret: ${INTERNAL_CLIENT_TRANSFER_SERVICE_SECRET}
            authorization-grant-type: client_credentials
            scope: internal
        provider:
          card-service:
            token-uri: https://auth-service:8443/auth/oauth/token

  kafka:
    bootstrap-servers: kafka:9092
    admin:
      auto-create: true
    consumer:
      group-id: transfer-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

feign:
  httpclient:
    enabled: true

card-service:
  url: https://card-service:8443

logging:
  level:
    root: INFO

security:
  jwt:
    expected-issuer: ${AUTH_JWT_ISSUER:auth-service}
    accepted-audiences: ${TRANSFER_JWT_ACCEPTED_AUDIENCES:bank-rest-api}
