package com.mike.transfer.error;

public enum ErrorType {
    ACCOUNT_NOT_FOUND,
    INSUFFICIENT_FUNDS,
    CURRENCY_MISMATCH,
    SAME_ACCOUNT_TRANSFER,
    INVALID_AMOUNT,
    IDEMPOTENCY_CONFLICT,
    CARD_NOT_FOUND,
    CARD_BLOCKED,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
