server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: true
    key-store: /certs/shared-services.p12
    key-store-password: ${SHARED_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: bank-shared-tls
  forward-headers-strategy: framework

spring:
  application:
    name: card-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-card:5432/card}
    username: ${SPRING_DATASOURCE_USERNAME:card}
    password: ${SPRING_DATASOURCE_PASSWORD:card}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth-service:8443/auth/jwks

  kafka:
    bootstrap-servers: kafka:9092
    admin:
      auto-create: true
    consumer:
      group-id: card-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO

security:
  jwt:
    expected-issuer: ${AUTH_JWT_ISSUER:auth-service}
    accepted-audiences: ${CARD_JWT_ACCEPTED_AUDIENCES:bank-rest-api,bank-rest-internal}
